# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import catalog_pb2 as catalog__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in catalog_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CatalogStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAllProducts = channel.unary_unary(
                '/catalog.Catalog/GetAllProducts',
                request_serializer=catalog__pb2.Empty.SerializeToString,
                response_deserializer=catalog__pb2.ProductsResponse.FromString,
                _registered_method=True)
        self.GetAllCategories = channel.unary_unary(
                '/catalog.Catalog/GetAllCategories',
                request_serializer=catalog__pb2.Empty.SerializeToString,
                response_deserializer=catalog__pb2.CategoriesResponse.FromString,
                _registered_method=True)
        self.SearchProducts = channel.unary_unary(
                '/catalog.Catalog/SearchProducts',
                request_serializer=catalog__pb2.SearchRequest.SerializeToString,
                response_deserializer=catalog__pb2.ProductsResponse.FromString,
                _registered_method=True)
        self.CreateProduct = channel.unary_unary(
                '/catalog.Catalog/CreateProduct',
                request_serializer=catalog__pb2.CreateProductRequest.SerializeToString,
                response_deserializer=catalog__pb2.ProductResponse.FromString,
                _registered_method=True)
        self.CreateCategory = channel.unary_unary(
                '/catalog.Catalog/CreateCategory',
                request_serializer=catalog__pb2.CreateCategoryRequest.SerializeToString,
                response_deserializer=catalog__pb2.CategoryResponse.FromString,
                _registered_method=True)
        self.UpdateProduct = channel.unary_unary(
                '/catalog.Catalog/UpdateProduct',
                request_serializer=catalog__pb2.UpdateProductRequest.SerializeToString,
                response_deserializer=catalog__pb2.ProductResponse.FromString,
                _registered_method=True)
        self.UpdateCategory = channel.unary_unary(
                '/catalog.Catalog/UpdateCategory',
                request_serializer=catalog__pb2.UpdateCategoryRequest.SerializeToString,
                response_deserializer=catalog__pb2.CategoryResponse.FromString,
                _registered_method=True)
        self.GetProduct = channel.unary_unary(
                '/catalog.Catalog/GetProduct',
                request_serializer=catalog__pb2.GetProductRequest.SerializeToString,
                response_deserializer=catalog__pb2.ProductResponse.FromString,
                _registered_method=True)
        self.GetCategory = channel.unary_unary(
                '/catalog.Catalog/GetCategory',
                request_serializer=catalog__pb2.GetCategoryRequest.SerializeToString,
                response_deserializer=catalog__pb2.CategoryResponse.FromString,
                _registered_method=True)
        self.DeleteProduct = channel.unary_unary(
                '/catalog.Catalog/DeleteProduct',
                request_serializer=catalog__pb2.DeleteProductRequest.SerializeToString,
                response_deserializer=catalog__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.DeleteCategory = channel.unary_unary(
                '/catalog.Catalog/DeleteCategory',
                request_serializer=catalog__pb2.DeleteCategoryRequest.SerializeToString,
                response_deserializer=catalog__pb2.DeleteResponse.FromString,
                _registered_method=True)


class CatalogServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAllProducts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllCategories(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchProducts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCategory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCategory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCategory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCategory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CatalogServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAllProducts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllProducts,
                    request_deserializer=catalog__pb2.Empty.FromString,
                    response_serializer=catalog__pb2.ProductsResponse.SerializeToString,
            ),
            'GetAllCategories': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllCategories,
                    request_deserializer=catalog__pb2.Empty.FromString,
                    response_serializer=catalog__pb2.CategoriesResponse.SerializeToString,
            ),
            'SearchProducts': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchProducts,
                    request_deserializer=catalog__pb2.SearchRequest.FromString,
                    response_serializer=catalog__pb2.ProductsResponse.SerializeToString,
            ),
            'CreateProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProduct,
                    request_deserializer=catalog__pb2.CreateProductRequest.FromString,
                    response_serializer=catalog__pb2.ProductResponse.SerializeToString,
            ),
            'CreateCategory': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCategory,
                    request_deserializer=catalog__pb2.CreateCategoryRequest.FromString,
                    response_serializer=catalog__pb2.CategoryResponse.SerializeToString,
            ),
            'UpdateProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProduct,
                    request_deserializer=catalog__pb2.UpdateProductRequest.FromString,
                    response_serializer=catalog__pb2.ProductResponse.SerializeToString,
            ),
            'UpdateCategory': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCategory,
                    request_deserializer=catalog__pb2.UpdateCategoryRequest.FromString,
                    response_serializer=catalog__pb2.CategoryResponse.SerializeToString,
            ),
            'GetProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProduct,
                    request_deserializer=catalog__pb2.GetProductRequest.FromString,
                    response_serializer=catalog__pb2.ProductResponse.SerializeToString,
            ),
            'GetCategory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCategory,
                    request_deserializer=catalog__pb2.GetCategoryRequest.FromString,
                    response_serializer=catalog__pb2.CategoryResponse.SerializeToString,
            ),
            'DeleteProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteProduct,
                    request_deserializer=catalog__pb2.DeleteProductRequest.FromString,
                    response_serializer=catalog__pb2.DeleteResponse.SerializeToString,
            ),
            'DeleteCategory': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCategory,
                    request_deserializer=catalog__pb2.DeleteCategoryRequest.FromString,
                    response_serializer=catalog__pb2.DeleteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'catalog.Catalog', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('catalog.Catalog', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Catalog(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAllProducts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalog.Catalog/GetAllProducts',
            catalog__pb2.Empty.SerializeToString,
            catalog__pb2.ProductsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllCategories(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalog.Catalog/GetAllCategories',
            catalog__pb2.Empty.SerializeToString,
            catalog__pb2.CategoriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchProducts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalog.Catalog/SearchProducts',
            catalog__pb2.SearchRequest.SerializeToString,
            catalog__pb2.ProductsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalog.Catalog/CreateProduct',
            catalog__pb2.CreateProductRequest.SerializeToString,
            catalog__pb2.ProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateCategory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalog.Catalog/CreateCategory',
            catalog__pb2.CreateCategoryRequest.SerializeToString,
            catalog__pb2.CategoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalog.Catalog/UpdateProduct',
            catalog__pb2.UpdateProductRequest.SerializeToString,
            catalog__pb2.ProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateCategory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalog.Catalog/UpdateCategory',
            catalog__pb2.UpdateCategoryRequest.SerializeToString,
            catalog__pb2.CategoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalog.Catalog/GetProduct',
            catalog__pb2.GetProductRequest.SerializeToString,
            catalog__pb2.ProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCategory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalog.Catalog/GetCategory',
            catalog__pb2.GetCategoryRequest.SerializeToString,
            catalog__pb2.CategoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalog.Catalog/DeleteProduct',
            catalog__pb2.DeleteProductRequest.SerializeToString,
            catalog__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCategory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalog.Catalog/DeleteCategory',
            catalog__pb2.DeleteCategoryRequest.SerializeToString,
            catalog__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
