FROM python:3.11.4

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY proto/auth.proto .

RUN python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. auth.proto

COPY services/auth.py .

CMD ["python", "auth.py"]