FROM python:3.11.4

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY proto/*.proto .
RUN python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. *.proto

COPY services/gateway.py .

CMD ["python", "gateway.py"]